// <copyright file="Achievements.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using Internal;

    /// <summary>
    /// Provides access to achievements registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Achievements
    {
        private static readonly UnifiedAchievement s_test = new UnifiedAchievement("Test",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_py27KIbEAIQAg"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_AMAZON
            ""
#else
            "Test"
#endif
            );

        public static UnifiedAchievement Test
        {
            get { return s_test; }
        }

        public static readonly UnifiedAchievement[] All =
        {
            s_test,
        };
    }
}
